apiVersion: v1
kind: Namespace
metadata:
  name: app-test-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test-1-deploy
  namespace: app-test-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-test-1
  template:
    metadata:
      labels:
        app: app-test-1
    spec:
      containers:
      - name: app-test-1
        image: nginx
        ports:
        - name: web
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-test-1
  name: app-test-1-svc
  namespace: app-test-1
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app-test-1
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.66.202
  type: LoadBalancer
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: app-test-1
  namespace: app-test-1
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`app-test-1.k8s.sohot.app`)
      services:
        - name: app-test-1-svc
          port: 80
  tls: {}